apiVersion: v1
kind: Pod
metadata:
  name: podscoped-proxy-client
spec:
  containers:
  - name: victim
    image: busybox:1.28
    command: ["sh", "-c", "echo 'Victim container is running'; sleep 3600"]
  - name: orchestrator
    image: ubuntu:22.04
    command:
    - "sh"
    - "-c"
    - |
      set -ex
      apt-get update && apt-get install -y curl
      
      echo "--- Downloading crictl ---"
      CRICTL_VERSION="v1.28.0"
      curl -L https://github.com/kubernetes-sigs/cri-tools/releases/download/$CRICTL_VERSION/crictl-$CRICTL_VERSION-linux-amd64.tar.gz --output crictl.tar.gz
      tar zxvf crictl.tar.gz
      
      SOCKET="unix:///run/cri-lite/dynamic-podscope/cri-lite.sock"
      
      echo "--- Listing containers to find victim ---"
      ./crictl --runtime-endpoint $SOCKET ps -a
      
      echo "--- Finding victim container ID ---"
      VICTIM_ID=$(./crictl --runtime-endpoint $SOCKET ps -a | grep 'victim' | awk '{print $1}')
      if [ -z "$VICTIM_ID" ]; then
        echo "Error: Could not find victim container ID!"
        exit 1
      fi
      echo "Found victim container ID: $VICTIM_ID"
      
      echo "--- Stopping victim container (should succeed) ---"
      ./crictl --runtime-endpoint $SOCKET stop "$VICTIM_ID"
      
      echo "--- Verifying victim container is stopped ---"
      # The grep should now return a non-zero exit code because the container is stopped
      if ./crictl --runtime-endpoint $SOCKET ps -a | grep "$VICTIM_ID" | grep -q 'Running'; then
        echo "Error: Victim container is still running!"
        exit 1
      else
        echo "Success: Victim container is stopped as expected."
      fi
      
      echo "--- Test complete, sleeping ---"
      sleep infinity
    volumeMounts:
    - name: cri-lite-podscoped-socket
      mountPath: /run/cri-lite/dynamic-podscope
  volumes:
  - name: cri-lite-podscoped-socket
    hostPath:
      path: /var/run/cri-lite/dynamic-podscope
      type: Directory
