name: CI
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-go@v6
      with:
        go-version: '1.24'
    - name: Build
      run: make build
    - name: Lint
      run: make lint
    - name: Test
      run: make test
