name: E2E
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  e2e:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: '1.24'

    - name: Install Linux dependencies for containerd
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          btrfs-progs \
          libbtrfs-dev \
          libseccomp2 \
          libseccomp-dev \
          socat

    - name: Checkout containerd
      uses: actions/checkout@v4
      with:
        repository: containerd/containerd
        path: containerd

    - name: Install containerd
      working-directory: containerd
      run: |
        make
        sudo -E PATH=$PATH make install

    - name: Install cni
      working-directory: containerd
      run: |
        sudo -E PATH=$PATH script/setup/install-cni $(grep containernetworking/plugins go.mod | awk '{print $2}')

    - name: Run e2e tests
      run: |
        set -e

        BDIR="/var/lib/containerd-critest"
        sudo mkdir -p ${BDIR}/{root,state}
        cat <<EOF | sudo tee ${BDIR}/config.toml
        version = 2
        [plugins."io.containerd.grpc.v1.cri"]
          sandbox_image = "k8s.gcr.io/pause:3.9"
          [plugins."io.containerd.grpc.v1.cri".containerd]
            snapshotter = "overlayfs"
            default_runtime_name = "runc"
            [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc]
              runtime_type = "io.containerd.runc.v2"
        EOF

        make build

        sudo rm -rf /etc/containerd
        sudo bash -c "/usr/local/bin/containerd --config ${BDIR}/config.toml -a ${BDIR}/c.sock -root ${BDIR}/root -state ${BDIR}/state -log-level debug &> ${BDIR}/containerd-cri.log &"

        for i in $(seq 1 15); do
          if sudo grep -q 'containerd successfully booted' ${BDIR}/containerd-cri.log; then
            echo "Containerd started successfully."
            break
          fi
          if [ $i -eq 15 ]; then
            echo "Timed out waiting for containerd to start."
            echo "--- containerd log ---"
            sudo cat ${BDIR}/containerd-cri.log
            exit 1
          fi
          sleep 1
        done

        sudo -E PATH=$PATH RUNTIME_ENDPOINT=unix:///${BDIR}/c.sock make test-e2e
        sudo pkill containerd
        sudo rm -rf ${BDIR}
