name: E2E
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: '1.24'

    - name: Install Linux dependencies for containerd
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          btrfs-progs \
          libbtrfs-dev \
          libseccomp2 \
          libseccomp-dev \
          socat

    - name: Checkout containerd
      uses: actions/checkout@v4
      with:
        repository: containerd/containerd
        path: containerd

    - name: Install containerd
      working-directory: containerd
      run: |
        make
        sudo -E PATH=$PATH make install

    - name: Install cni
      working-directory: containerd
      run: |
        sudo -E PATH=$PATH script/setup/install-cni $(grep containernetworking/plugins go.mod | awk '{print $2}')

    - name: Run e2e tests
      run: |
        sudo containerd &
        sleep 5
        sudo -E PATH=$PATH make test-e2e
        sudo pkill containerd
